import sys
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import ( QApplication, QCheckBox, QComboBox, QDial,
    QDoubleSpinBox, QLabel, QLCDNumber, QLineEdit, QMainWindow, QProgressBar,
    QPushButton, QRadioButton, QSlider, QSpinBox, QVBoxLayout, QHBoxLayout,
    QGridLayout, QWidget, QFormLayout )
class Window(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Character Sheet")
        self.resize(1200, 600)
        layout = QGridLayout()
        Classes = QComboBox()
        Classes.addItems(["Academics", "Burghers", "Courtiers", "Peasants",
            "Rangers", "Riverfolk", "Rouges", "Warriors"])
        Species = QComboBox()
        Species.addItems(["Human", "Dwarf", "Hlafling", "High Elf", "Wood Elf"])
        Level = QComboBox()
        Level.addItems(["1", "2", "3", "4"])
        Status = QComboBox()
        Status.addItems(["Brass", "Silver", "Gold"])
        SLevel = QComboBox()
        SLevel.addItems(["1", "2", "3", "4", "5"])
        layout.addWidget(QLabel("Name: "), 0, 0)
        Name = QLineEdit()
        Name.setMinimumWidth(500)
        layout.addWidget(Name , 0, 1)
        Spec = QFormLayout()
        Spec.addRow(QLabel("Species: "), Species)
        layout.addLayout(Spec, 0, 2)
        Cla = QFormLayout()
        Cla.addRow(QLabel("Class: "), Classes)
        layout.addLayout(Cla, 0, 3)
        layout.addWidget(QLabel("Career: "), 1, 0)
        layout.addWidget(QLineEdit(), 1 , 1)
        CarL = QFormLayout()
        CarL.addRow(QLabel("Career Level: "), Level)
        layout.addLayout(CarL, 1, 2)
        layout.addWidget(QLabel("Career Path: "), 2, 0)
        layout.addWidget(QLineEdit(), 2, 1)
        layout.addWidget(QLabel("Status: "), 2, 2)
        Stat = QFormLayout()
        Stat.addRow(Status, SLevel)
        layout.addLayout(Stat, 2, 3)
        Age = QFormLayout()
        Height = QFormLayout()
        Hair = QFormLayout()
        Eyes = QFormLayout()
        Chr1 = QLineEdit()
        Chr1.setFixedWidth(60)
        Age.addRow("Age: ", Chr1)
        Chr2 = QLineEdit()
        Chr2.setFixedWidth(120)
        Height.addRow("Height: ", Chr2)
        Chr3 = QLineEdit()
        Chr3.setFixedWidth(240)
        Hair.addRow("Hair: ", Chr3)
        Chr4 = QLineEdit()
        Chr4.setFixedWidth(240)
        Eyes.addRow("Eyes: ", Chr4)
        layout.addLayout(Age , 3, 0)
        layout.addLayout(Height , 3, 1)
        layout.addLayout(Hair , 3, 2)
        layout.addLayout(Eyes , 3, 3)
        self.setLayout(layout)
if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = Window()
    window.show()
    sys.exit(app.exec_())
